#!/usr/bin/env node
/**
 * Combines character batch files into a single characters.js
 * Run this before build.js if characters.js doesn't exist yet
 */

const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, 'data');
const allCharacters = [];

// Character batch files and their export names
const batches = [
  { file: 'characters-bb.js', key: 'breakingBadCharacters' },
  { file: 'characters-got.js', key: 'gotCharacters' },
  { file: 'characters-st.js', key: 'stCharacters' },
  { file: 'characters-office-succ.js', keys: ['officeCharacters', 'successionCharacters'] },
  { file: 'characters-wed-bear.js', keys: ['wednesdayCharacters', 'bearCharacters'] },
  { file: 'characters-sg-br-tlou.js', keys: ['squidGameCharacters', 'bridgertonCharacters', 'tlouCharacters'] },
];

batches.forEach(batch => {
  const filePath = path.join(dataDir, batch.file);
  if (!fs.existsSync(filePath)) {
    console.warn(`Warning: ${batch.file} not found, skipping`);
    return;
  }
  try {
    const mod = require(filePath);
    if (batch.key) {
      const chars = mod[batch.key];
      if (Array.isArray(chars)) {
        allCharacters.push(...chars);
        console.log(`  Loaded ${chars.length} characters from ${batch.file} (${batch.key})`);
      }
    }
    if (batch.keys) {
      batch.keys.forEach(k => {
        const chars = mod[k];
        if (Array.isArray(chars)) {
          allCharacters.push(...chars);
          console.log(`  Loaded ${chars.length} characters from ${batch.file} (${k})`);
        }
      });
    }
  } catch (e) {
    console.warn(`Error loading ${batch.file}: ${e.message}`);
  }
});

console.log(`\nTotal characters: ${allCharacters.length}`);

// Write combined file
const output = `// Auto-generated combined characters file
// Generated by combine-data.js on ${new Date().toISOString()}

const characters = ${JSON.stringify(allCharacters, null, 2)};

module.exports = { characters };
`;

fs.writeFileSync(path.join(dataDir, 'characters.js'), output, 'utf8');
console.log(`Written to data/characters.js (${allCharacters.length} characters)`);
