#!/usr/bin/env node
/**
 * Combines character batch files into a single characters.js
 * and actor batch files into a single combined actors file.
 * Run this before build.js if characters.js doesn't exist yet
 */

const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, 'data');

// ========== COMBINE CHARACTERS ==========
const allCharacters = [];

const charBatches = [
  { file: 'characters-bb.js', key: 'breakingBadCharacters' },
  { file: 'characters-got.js', key: 'gotCharacters' },
  { file: 'characters-st.js', key: 'stCharacters' },
  { file: 'characters-office-succ.js', keys: ['officeCharacters', 'successionCharacters'] },
  { file: 'characters-wed-bear.js', keys: ['wednesdayCharacters', 'bearCharacters'] },
  { file: 'characters-sg-br-tlou.js', keys: ['squidGameCharacters', 'bridgertonCharacters', 'tlouCharacters'] },
  // Batch 2 - expansion shows
  { file: 'characters-friends-sopranos.js', keys: ['friendsCharacters', 'sopranosCharacters'] },
  { file: 'characters-ozark-tedlasso.js', keys: ['ozarkCharacters', 'tedLassoCharacters'] },
  { file: 'characters-euphoria-mando.js', keys: ['euphoriaCharacters', 'mandalorianCharacters'] },
  { file: 'characters-peaky-crown.js', keys: ['peakyCharacters', 'crownCharacters'] },
  { file: 'characters-yellowstone-schitts.js', keys: ['yellowstoneCharacters', 'schittsCreekCharacters'] },
];

console.log('=== Combining Character Data ===');
charBatches.forEach(batch => {
  const filePath = path.join(dataDir, batch.file);
  if (!fs.existsSync(filePath)) {
    console.warn(`Warning: ${batch.file} not found, skipping`);
    return;
  }
  try {
    const mod = require(filePath);
    if (batch.key) {
      const chars = mod[batch.key];
      if (Array.isArray(chars)) {
        allCharacters.push(...chars);
        console.log(`  Loaded ${chars.length} characters from ${batch.file} (${batch.key})`);
      }
    }
    if (batch.keys) {
      batch.keys.forEach(k => {
        const chars = mod[k];
        if (Array.isArray(chars)) {
          allCharacters.push(...chars);
          console.log(`  Loaded ${chars.length} characters from ${batch.file} (${k})`);
        }
      });
    }
  } catch (e) {
    console.warn(`Error loading ${batch.file}: ${e.message}`);
  }
});

console.log(`\nTotal characters: ${allCharacters.length}`);

const charOutput = `// Auto-generated combined characters file
// Generated by combine-data.js on ${new Date().toISOString()}

const characters = ${JSON.stringify(allCharacters, null, 2)};

module.exports = { characters };
`;

fs.writeFileSync(path.join(dataDir, 'characters.js'), charOutput, 'utf8');
console.log(`Written to data/characters.js (${allCharacters.length} characters)\n`);

// ========== COMBINE ACTORS ==========
const allActors = [];

const actorBatches = [
  { file: 'actors.js', key: 'actors' },
  { file: 'actors-batch2.js', key: 'actors2' },
];

console.log('=== Combining Actor Data ===');
actorBatches.forEach(batch => {
  const filePath = path.join(dataDir, batch.file);
  if (!fs.existsSync(filePath)) {
    console.warn(`Warning: ${batch.file} not found, skipping`);
    return;
  }
  try {
    const mod = require(filePath);
    const items = mod[batch.key];
    if (Array.isArray(items)) {
      allActors.push(...items);
      console.log(`  Loaded ${items.length} actors from ${batch.file}`);
    }
  } catch (e) {
    console.warn(`Error loading ${batch.file}: ${e.message}`);
  }
});

// Deduplicate actors by slug (in case shared actors like Pedro Pascal appear in both batches)
const seenSlugs = new Set();
const dedupedActors = [];
allActors.forEach(a => {
  if (!seenSlugs.has(a.slug)) {
    seenSlugs.add(a.slug);
    dedupedActors.push(a);
  }
});

console.log(`\nTotal actors: ${dedupedActors.length} (after deduplication)`);

const actorOutput = `// Auto-generated combined actors file
// Generated by combine-data.js on ${new Date().toISOString()}

const actors = ${JSON.stringify(dedupedActors, null, 2)};

module.exports = { actors };
`;

fs.writeFileSync(path.join(dataDir, 'actors-combined.js'), actorOutput, 'utf8');
console.log(`Written to data/actors-combined.js (${dedupedActors.length} actors)\n`);
